In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("mnist_train.csv")

In [3]:
df.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier

In [7]:
lor = LogisticRegression()
dtc = DecisionTreeClassifier()

In [8]:
lor.fit(X_train,y_train)
dtc.fit(X_train,y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [9]:
y_pred = lor.predict(X_test)
y_pred1 = dtc.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix

print('LogisticRegression:',accuracy_score(y_test,y_pred))
print('DecisionTreeClassifier:',accuracy_score(y_test,y_pred1))

LogisticRegression: 0.92225
DecisionTreeClassifier: 0.8670833333333333


In [11]:
#LogisticRegression

pd.DataFrame(confusion_matrix(y_test,y_pred))

0     1     2     3     4    5     6     7     8     9
0  1139     0     6     3     4    4     5     4     8     2
1     0  1283     8     6     2    3     1     2    13     4
2     1    18  1054    14    13    5    18    17    29     5
3     4     8    36  1090     1   32     2     9    22    15
4     4     2     5     2  1108    3     9     4     7    32
5    15     5    14    39     9  961    11     4    38     8
6    11     0    15     1     9   14  1120     2     5     0
7     5     7    15     9    10    2     0  1209     6    36
8    10    13    14    31     9   32    10     4  1028     9
9     5     4     5    14    28   10     0    39    14  1075

In [12]:
#DecisionTreeClassifier

pd.DataFrame(confusion_matrix(y_test,y_pred1))

0     1     2     3     4    5     6     7    8     9
0  1071     1    14     9     3   28    19     8   14     8
1     1  1271     6    10     3    7     7     2   13     2
2    19    13  1001    23    19    9    10    24   41    15
3    17     7    33  1008    10   62     5    12   29    36
4     1     4    10     7  1032    7    10    17   19    69
5    17    12    16    55     9  905    29     7   33    21
6    16    10    16     5    24   25  1050     5   20     6
7     5    12    25    21    10   13     4  1170   11    28
8    21    23    42    39    32   39    26    12  895    31
9     9    12    10    16    48   17     5    33   42  1002

In [13]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [14]:
#for LogisticRegression

In [15]:
print(precision_score(y_test,y_pred,average='weighted'))
print(precision_score(y_test,y_pred,average='macro'))

0.9220843650924354
0.9214273709366504


In [16]:
print(recall_score(y_test,y_pred,average='weighted'))
print(recall_score(y_test,y_pred,average='macro'))

0.92225
0.9213299366860115


In [17]:
print(f1_score(y_test,y_pred,average='weighted'))
print(f1_score(y_test,y_pred,average='macro'))

0.9221219635238594
0.9213314758432045


In [18]:
#for DecisionTreeClassifier

In [19]:
precision_score(y_test,y_pred1,average='weighted')

0.866749927630678

In [20]:
print(precision_score(y_test,y_pred1,average='weighted'))
print(precision_score(y_test,y_pred1,average='macro'))

0.866749927630678
0.8652625808059058


In [21]:
print(recall_score(y_test,y_pred1,average='weighted'))
print(recall_score(y_test,y_pred1,average='macro'))

0.8670833333333333
0.8653295793213014


In [22]:
print(f1_score(y_test,y_pred1,average='weighted'))
print(f1_score(y_test,y_pred1,average='macro'))

0.8668372265353445
0.8652182147321963


In [23]:
#LogisticRegression

precision_score(y_test,y_pred,average=None)

array([0.95393635, 0.95746269, 0.89931741, 0.90157155, 0.92875105,
       0.90150094, 0.95238095, 0.93431221, 0.87863248, 0.90640809])

In [24]:
#LogisticRegression

recall_score(y_test,y_pred,average=None)

array([0.9693617 , 0.97049924, 0.89778535, 0.89417555, 0.94217687,
       0.87047101, 0.95157179, 0.93071594, 0.8862069 , 0.90033501])

In [25]:
#LogisticRegression

f1_score(y_test,y_pred,average=None)

array([0.96158717, 0.96393689, 0.89855072, 0.89785832, 0.93541579,
       0.88571429, 0.9519762 , 0.93251061, 0.88240343, 0.90336134])

In [26]:
#DecisionTreeClassifier

precision_score(y_test,y_pred1,average=None)

array([0.90994053, 0.93113553, 0.85336743, 0.84492875, 0.86722689,
       0.81384892, 0.90128755, 0.90697674, 0.80125336, 0.8226601 ])

In [27]:
#DecisionTreeClassifier

recall_score(y_test,y_pred1,average=None)

array([0.91148936, 0.96142209, 0.85264055, 0.8269073 , 0.87755102,
       0.81974638, 0.89209856, 0.90069284, 0.77155172, 0.83919598])

In [28]:
#DecisionTreeClassifier

f1_score(y_test,y_pred1,average=None)

array([0.91071429, 0.94603647, 0.85300383, 0.8358209 , 0.87235841,
       0.816787  , 0.89666951, 0.90382387, 0.78612209, 0.83084577])

In [29]:
from sklearn.metrics import classification_report

In [30]:
#LogisticRegression

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1175
           1       0.96      0.97      0.96      1322
           2       0.90      0.90      0.90      1174
           3       0.90      0.89      0.90      1219
           4       0.93      0.94      0.94      1176
           5       0.90      0.87      0.89      1104
           6       0.95      0.95      0.95      1177
           7       0.93      0.93      0.93      1299
           8       0.88      0.89      0.88      1160
           9       0.91      0.90      0.90      1194

    accuracy                           0.92     12000
   macro avg       0.92      0.92      0.92     12000
weighted avg       0.92      0.92      0.92     12000



In [31]:
#DecisionTreeClassifier

print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91      1175
           1       0.93      0.96      0.95      1322
           2       0.85      0.85      0.85      1174
           3       0.84      0.83      0.84      1219
           4       0.87      0.88      0.87      1176
           5       0.81      0.82      0.82      1104
           6       0.90      0.89      0.90      1177
           7       0.91      0.90      0.90      1299
           8       0.80      0.77      0.79      1160
           9       0.82      0.84      0.83      1194

    accuracy                           0.87     12000
   macro avg       0.87      0.87      0.87     12000
weighted avg       0.87      0.87      0.87     12000

