In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [4]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
lor = LogisticRegression()
dtc = DecisionTreeClassifier()

In [8]:
lor.fit(X_train,y_train)
dtc.fit(X_train,y_train)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [9]:
y_pred = lor.predict(X_test)
y_pred1 = dtc.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix

print('LogisticRegression:',accuracy_score(y_test,y_pred))
print('DecisionTreeClassifier:',accuracy_score(y_test,y_pred1))

LogisticRegression: 0.7853658536585366
DecisionTreeClassifier: 0.9853658536585366


In [11]:
#LogisticRegression

confusion_matrix(y_test,y_pred)

array([[71, 31],
       [13, 90]], dtype=int64)

In [12]:
#DecisionTreeClassifier

confusion_matrix(y_test,y_pred1)

array([[102,   0],
       [  3, 100]], dtype=int64)

In [13]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [21]:
print('For LogisticRegression')
print(confusion_matrix(y_test,y_pred))
print('-'*50)
print('precision score:',precision_score(y_test,y_pred))
print('recall score:',recall_score(y_test,y_pred))
print('f1 score:',f1_score(y_test,y_pred))

For LogisticRegression
[[71 31]
 [13 90]]
--------------------------------------------------
precision score: 0.743801652892562
recall score: 0.8737864077669902
f1 score: 0.8035714285714285


In [22]:
print('For DecisionTreeClassifier')
print(confusion_matrix(y_test,y_pred1))
print('-'*50)
print('precision score:',precision_score(y_test,y_pred1))
print('recall score:',recall_score(y_test,y_pred1))
print('f1 score:',f1_score(y_test,y_pred1))

For DecisionTreeClassifier
[[102   0]
 [  3 100]]
--------------------------------------------------
precision score: 1.0
recall score: 0.970873786407767
f1 score: 0.9852216748768473


In [23]:
precision_score(y_test,y_pred1,average=None)

array([0.97142857, 1.        ])

In [24]:
recall_score(y_test,y_pred1,average=None)

array([1.        , 0.97087379])